FROM java:8
COPY C:/windows/system32/config/systemprofile/AppData/Local/Jenkins/\.jenkins/workspace/HomeBanking/HomeBanking/target/HomeBanking-0.0.1-SNAPSHOT.jar HomeBanking-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","HomeBanking-0.0.1-SNAPSHOT.jar"]