DROP TABLE IF EXISTS USERS;
  
CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,	
  Nom VARCHAR(250) NOT NULL,
  Prenom VARCHAR(250) NOT NULL,
  Date_de_naissance DATE  DEFAULT NULL,
  Date_debut_contrat TIMESTAMP  DEFAULT NULL,
  Date_fin_contrat TIMESTAMP  DEFAULT NULL
);