DROP TABLE IF EXISTS USERS;
  
CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,	
  firstName VARCHAR(250) NOT NULL,
  secondName VARCHAR(250) NOT NULL,
  birthDay DATE  DEFAULT NULL,
  startDay TIMESTAMP  DEFAULT NULL,
  endDay TIMESTAMP  DEFAULT NULL
);